import fs from "node:fs";
import path from "node:path";
import Database from "better-sqlite3";

// Server-only: better-sqlite3 is a native module. Never import this from a client component.

/** Generated by `npm run seed` at build time and shipped with the deployment. */
export const DB_PATH = path.join(process.cwd(), "data", "voltkart.db");
const SCHEMA_PATH = path.join(process.cwd(), "scripts", "schema.sql");

let runtimeDb: Database.Database | null = null;

/**
 * Read-only handle for the app. Vercel's filesystem is read-only at runtime, so the
 * app must never write; opening readonly turns any accidental write into an error.
 */
export function getDb(): Database.Database {
  if (runtimeDb) return runtimeDb;
  if (!fs.existsSync(DB_PATH)) {
    throw new Error(`Database not found at ${DB_PATH}. Run \`npm run seed\` first.`);
  }
  runtimeDb = new Database(DB_PATH, { readonly: true, fileMustExist: true });
  return runtimeDb;
}

/**
 * Seed script only. Deletes any existing file and builds a fresh database from
 * schema.sql, so every seed run is reproducible from scratch.
 */
export function createDb(filePath: string = DB_PATH): Database.Database {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.rmSync(filePath, { force: true });
  const db = new Database(filePath);
  db.pragma("foreign_keys = ON");
  db.exec(fs.readFileSync(SCHEMA_PATH, "utf8"));
  return db;
}
